tunnel: b792e042-910a-47d2-bb15-38296322c12b
credentials-file: C:\Users\sujee\.cloudflared\b792e042-910a-47d2-bb15-38296322c12b.json

ingress:
  - hostname: resolve.kharidwise.com
    service: http://localhost:3000
  - service: http_status:404
